### ISSUE TITLE
Choose track colours

### ISSUE THREAD

**Issue by bernardo-de-almeida** [harbourlab/SparK#1]
Is it possible to choose the colours of the different tracks when plotting multiple ones (e.g. your example of a plot of 4 ChIP-seq tracks with standard settings)?

Thanks

**Comment by harbourlab** [comment]
Let me implement that real quick. Should be done in couple of hours.

**Comment by harbourlab** [comment]
Should work now. Just uploaded SparK version 2.4.2, which has that implemented. Enter one hex color with the "-f" option. Let me know if other issues arise! Cheers

**Comment by bernardo-de-almeida** [comment]
Very cool, thanks!
