### ISSUE TITLE
Junctions

### ISSUE THREAD

**Issue by bvaldebenitom** [harbourlab/SparK#10]
Hi!

I have been using SparK with good results for a while. Is there any development for showing splice junctions from RNA-Seq data? (i.e., sashimi plots)

Best regards!

**Comment by harbourlab** [comment]
Hi! I'm happy you find SparK useful! Unfortunately sashimi plots are not integrated. We might integrate this in future, but it's not envisioned as of now. Only thing you can do at the moment is plot all known isoforms of your gene of interest with the "-dt all" setting, to visualize which exons are expressed. You'd probably have to add this information manually in Illustrator or such. Cheers, Stefan
