### ISSUE TITLE
range of y-axis 

### ISSUE THREAD

**Issue by karini925** [harbourlab/SparK#3]
Is there any way to control the range of the y-axis? I am comparing a histone mark across three treatments and would like the y-axis to display the same range, is that possible with this tool? thanks! also while I am here, any chance coordinates can be printed out?
[test_case.pdf](https://github.com/harbourlab/SparK/files/4256913/test_case.pdf)

**Comment by harbourlab** [comment]
Hi! Yes, just do autoscale (-gs yes) that will result in all y-axis to be the same. Let me know if that works for you! I can implement the coordinates to be printed out, thats a great idea! Will do so in a week or so.. Further, your scalebar is missing.. did you remove that? Also there are no labels for the group.. I'm assuming you removed them or did not set them?

**Comment by karini925** [comment]
The coordinates would be awesome to add on! My scalebar is indeed missing and I am not sure why, it is set at the default "yes". Any thought as to why this may be? For y-axis, I am wondering about setting it to a certain value as the values range from plot to plot (see attached). Ideally I would set the range in both plots to 0-2.5, is that at all possible? thanks !!  
[test_case_spark.pdf](https://github.com/harbourlab/SparK/files/4268439/test_case_spark.pdf)

**Comment by harbourlab** [comment]
Did you try "-gs yes"? That should do exactly what you need and scale the y-axis. I'll look into why the scale bar is missing..

**Comment by karini925** [comment]
thanks! and yes, I did "-gs yes" but the two plots still have different y-axis ranges. 

`python $spark \
-pr $region  \
-cf 009_broad_treat_pileup.bdg 021_broad_treat_pileup.bdg \
-tf 012_broad_treat_pileup.bdg 024_broad_treat_pileup.bdg \
-tg 1 1 \
-cg 1 1 \
-gs yes \
-gl H3K27AC \
-dg $region_name \
-gff $gtf \
-pt STD \
-l LEN COMBO \
-w 200 \
-f 005CFF CE358B \
-o ${output}/H3K27ac_COMBO_len_${region_name} \
-scale yes \
-bed $consensus_peaks $methy \
-bedcol EF1414 FFBC00`

**Comment by harbourlab** [comment]
I see.. you are plotting both plots individually. What you need to do - and this is way easier - is plot all at once. Use this:

-cf file1.bdg file2.bdg file3.bdg file4.bdg
-tf file5.bdg file6.bdg file7.bdg file8.bdg
-tg 1 1 2 2
-cg 1 1 2 2

This way, the first two files in -cf and -tf will go to the first plot, and the last two into the second plot. And with "-gs yes" SparK will autoscale both. Let me know if that works!

**Comment by harbourlab** [comment]
Were you able to try? I can not reproduce your missing scalebar. Let me know if that is still occurring!

**Comment by karini925** [comment]
thanks - yes it works! for some reason the scale bar wasn't visible but when I put the svg into Affinity Designer I was able see it

**Comment by harbourlab** [comment]
Ah perfect! Glad it works. I'll be implementing more ways of defining the y-axis soon, and plotting the coordinates. Should be done in next couple days.

**Comment by karini925** [comment]
Awesome, thank you!

**Comment by harbourlab** [comment]
just uploaded version 2.5 which has more options to customize the y-axis.. need to do a little spacing tweek for some cases but should work fine for most.
