### ISSUE TITLE
Gene body could not be plotted correctly

### ISSUE THREAD

**Issue by lz43771** [harbourlab/SparK#4]
Hi,

I tried to plot ATAC-Seq and RNA-Seq data together. While the track looks great, the gene body/transcript could not be visualized correctly.  The exons are plotted while all the introns are not (so there is no line connecting the exons). I tried multiple ways but the issue still remains.

I tried -dg -dt -wg. None of them solved this problem. Here is the code I used:

python SparK.py \
-pr chr8:25818128-26065154 \
-cf d0.CallPeak_treat_pileup.bdg d4.CallPeak_treat_pileup.bdg d8.CallPeak_treat_pileup.bdg \
d15.CallPeak_treat_pileup.bdg d20.CallPeak_treat_pileup.bdg d24.CallPeak_treat_pileup.bdg \
-gff hg38.ncbiRefSeq.gtf \
-gl D0 D4 D8 D15 D20 D24 \
-dg EBF2 \
-gs yes \
-o EBF2_tes1

**Comment by harbourlab** [comment]
Hi! 

I checked with some data from me and the gene plots correctly. I believe the problem lies with the gtf file you are using. Please follow the link on the SparK site to the GENCODE site, and download the gff file for hg38 (https://www.gencodegenes.org/human/release_24.html). Also make sure to run the latest version of SparK (2.5.1). Let me know if that solves the problem for you!

Cheers,
Stefan

**Comment by harbourlab** [comment]
I'm closing this issue, but let me know if you have any problems!

**Comment by lz43771** [comment]
Hi Stefan,

Thank you for your reply and I am really appreciated for your help!

I was writing my paper and just got time to test what you suggested. I tried multiple gff3 and gtf files (gencode, NCBIrefseq, ensemble) . Currently, only the primary assemble gtf from the gencode works for me and I get the gene/transcript graphing correctly.

I noticed you wrote notification for the gff files in the Github page. All the gff3/gtf files I used seem to meet the requirement. I have no idea why they didn’t work out. I attached 2 pdf with result I got when using the same code but different gtf/gff.


Best,
Brian



On May 4, 2020, at 12:33 PM, Harbour Ocular Oncology Laboratory <notifications@github.com<mailto:notifications@github.com>> wrote:

[EXTERNAL SENDER - PROCEED CAUTIOUSLY]



I'm closing this issue, but let me know if you have any problems!

**Comment by harbourlab** [comment]
Hi Brian,

I am happy that the issue has resolved! Not sure why the other files have not worked. Sop the GENCODE gff file and the GENCODE gtf file did both work? Or only one of both?

Cheers
Stefan

________________________________________________________________
Stefan Kurtenbach
Assistant Scientist
Harbour Ocular Oncology Laboratory
University of Miami Miller School of Medicine
Biomedical Research Building
Room 832, Suite H-I
1501 NW 10th Avenue
Miami, FL 33136

305-326-6020 lab
786-252-4379 cell

On May 4, 2020, at 10:47 PM, lz43771 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Stefan,

Thank you for your reply and I am really appreciated for your help!

I was writing my paper and just got time to test what you suggested. I tried multiple gff3 and gtf files (gencode, NCBIrefseq, ensemble) . Currently, only the primary assemble gtf from the gencode works for me and I get the gene/transcript graphing correctly.

I noticed you wrote notification for the gff files in the Github page. All the gff3/gtf files I used seem to meet the requirement. I have no idea why they didn’t work out. I attached 2 pdf with result I got when using the same code but different gtf/gff.


Best,
Brian



On May 4, 2020, at 12:33 PM, Harbour Ocular Oncology Laboratory <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

[EXTERNAL SENDER - PROCEED CAUTIOUSLY]



I'm closing this issue, but let me know if you have any problems!

**Comment by lz43771** [comment]
Hi Stefan,

Only the gtf worked for me. The gff3 could not generate the transcript.

Best,
Brian
________________________________

**Comment by harbourlab** [comment]
Thank you for letting me know Brian. I am not sure what changed, but seems gtf files are the only ones working now. I will make an update on the site to state this. Thanks again!

**Comment by lz43771** [comment]
Hi Stefan,

May I know if your spark paper has been accepted or not? I am working my reference list and would like to add it. May I know you have any suggestion on how to cite it?

Best,
Brian

On May 5, 2020, at 6:29 PM, Harbour Ocular Oncology Laboratory <notifications@github.com<mailto:notifications@github.com>> wrote:

[EXTERNAL SENDER - PROCEED CAUTIOUSLY]



Thank you for letting me know Brian. I am not sure what changed, but seems gtf files are the only ones working now. I will make an update on the site to state this. Thanks again!

**Comment by harbourlab** [comment]
Hi Brian! Thank you! I have not submitted it to a peer-reviewed journal yet, but I would be grateful if you could cite the biorxiv paper! 

https://www.biorxiv.org/content/10.1101/845529v1

You can download a reference there and import it in endnote or such!

Thanks again!
Stefan

**Comment by lz43771** [comment]
Thank you Stefan. Will do as you recommend. I really like this tool and it is really helpful!

On May 7, 2020, at 5:12 PM, Harbour Ocular Oncology Laboratory <notifications@github.com<mailto:notifications@github.com>> wrote:

[EXTERNAL SENDER - PROCEED CAUTIOUSLY]



Hi Brian! Thank you! I have not submitted it to a peer-reviewed journal yet, but I would be grateful if you could cite the biorxiv paper!

https://www.biorxiv.org/content/10.1101/845529v1

You can download a reference there and import it in endnote or such!

Thanks again!
Stefan

**Comment by harbourlab** [comment]
Thank you! I am happy you find it useful! Let me know if you need anything down the road and good luck with your publication!!

Cheers
Stefan

________________________________________________________________
Stefan Kurtenbach
Assistant Scientist
Harbour Ocular Oncology Laboratory
University of Miami Miller School of Medicine
Biomedical Research Building
Room 832, Suite H-I
1501 NW 10th Avenue
Miami, FL 33136

305-326-6020 lab
786-252-4379 cell

On May 7, 2020, at 5:14 PM, lz43771 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you Stefan. Will do as you recommend. I really like this tool and it is really helpful!

On May 7, 2020, at 5:12 PM, Harbour Ocular Oncology Laboratory <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

[EXTERNAL SENDER - PROCEED CAUTIOUSLY]



Hi Brian! Thank you! I have not submitted it to a peer-reviewed journal yet, but I would be grateful if you could cite the biorxiv paper!

https://www.biorxiv.org/content/10.1101/845529v1

You can download a reference there and import it in endnote or such!

Thanks again!
Stefan
