### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by mdidish** [harbourlab/SparK#8]
Dear,
Thank you for you nice tool.
However I have a syntax error at line 799
```
write_to_file('''<text text-anchor="''' + text_anchor + '''''''" font-family="Arial" x="''' + str(x_value_chr_label) + '''" y="''' + str(y_value_chr_label) + '''" font-size="7" >Chr''' + str(region[0]) + ''': ''' + str(f"{region[1]:,}") + '''-''' + str(f"{region[2]:,}") + '''</text>''')
```

I don't know python so i don't know how to avoid this problem. I tried to replace
```
"''' + text_anchor + '''''''"
```
by
```
"''' + text_anchor + '''"
```
but without success.

Thank you for your help.

Edit: format modification

**Comment by harbourlab** [comment]
Hi! Can you copy paste the exact line of code you are using to execute SparK? Thanks!

**Comment by mdidish** [comment]
I just execute this test line (all files are in the same folder) :
`python ./SparK.py -pr chr12:6520512-6640512 -cf WTpalm3.bdg WTbsa1.bdg`

**Comment by harbourlab** [comment]
Thanks! So you are getting a good output on the computer where it works?

Also, what does the error message say exactly on the computer where it does not work?

**Comment by mdidish** [comment]
I'm currently try different parameters on the computer where it works, it sounds very good!

Concerning the error message, I don't have more information than that:
```
File "/home/mdidish/ATAC/spark/SparK.py", line 799
    write_to_file('''<text text-anchor="''' + text_anchor + ''''''" font-family="Arial" x="''' + str(x_value_chr_label) + '''" y="''' + str(y_value_chr_label) + '''" font-size="7" >Chr''' + str(region[0]) + ''': ''' + str(f"{region[1]:,}") + '''-''' + str(f"{region[2]:,}") + '''</text>''')
                                                                                     ^
```

**Comment by harbourlab** [comment]
Glad it works for you! I think that somehow its a python version issue, as it runs fine on your other machine. If you have any more problems let me know!
