### ISSUE TITLE
Able to plot only exons?

### ISSUE THREAD

**Issue by katiearacena** [harbourlab/SparK#9]
Hello, thank you for the awesome plotting tool! I am wondering if it is possible to only plot RNAseq reads mapping to exons. Perhaps I can subset on this using the GTF file similar to plotting just one transcript?

**Comment by harbourlab** [comment]
Hi! You should be able to do this with bedtools intersect. Check it out here.. https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html#bed-output-bed-format-when-using-bam-input  Only thing you need is a bed files that contains your exons, and you could intersect it with the RNAseq Bedgraph.

**Comment by katiearacena** [comment]
Success! Thank you very much for pointing me in the right direction!

**Comment by harbourlab** [comment]
Perfect! Glad it works out! Always looking forward to see more SparK plots! ;) Reach out any time!
